apiVersion: v1
kind: Service
metadata:
  name: chrome-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: chrome-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrome-api
  template:
    metadata:
      labels:
        app: chrome-api
    spec:
      containers:
        - name: chrome-api
          image: docker.pkg.github.com/sublayerio/chrome-api/chrome-api:v1.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
